# Generated by Django 4.2.29 on 2026-04-03 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name_tr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('icon', models.CharField(default='sparkles', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_hotel_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=120)),
                ('nightly_price_per_person', models.PositiveIntegerField()),
                ('currency', models.CharField(default='TRY', max_length=5)),
                ('rating', models.FloatField(default=0)),
                ('sponsored', models.BooleanField(default=False)),
                ('family_friendly', models.BooleanField(default=True)),
                ('distance_to_center_km', models.FloatField(default=0)),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('payment_succeeded', 'Payment succeeded'), ('payment_failed', 'Payment failed'), ('booking_confirmed', 'Booking confirmed'), ('booking_cancelled', 'Booking cancelled')], default='pending_payment', max_length=30)),
                ('payment_provider', models.CharField(default='booking_demand_partner', max_length=100)),
                ('payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='api.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('provider_name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=120)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('price_adult', models.PositiveIntegerField(default=0)),
                ('price_child', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='TRY', max_length=5)),
                ('family_friendly', models.BooleanField(default=True)),
                ('distance_km', models.FloatField(default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='tours', to='api.activitycategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='budget_type',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='children',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='city',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='itinerary_data',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='start_date',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='confirmed_plan_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='options_payload',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='source_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='UserLegalConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField()),
                ('version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_consents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TourReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('hotel_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_reservations', to='api.hotelreservation')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='api.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FunnelDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('budget_type', models.CharField(choices=[('luxury', 'Luxury'), ('economy', 'Economy'), ('cheap', 'Cheap')], max_length=20)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=2)),
                ('selected_city', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_draft', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
