# Generated by Django 4.2.29 on 2026-04-03 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activitycategory_hotel_hotelreservation_tour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='funneldraft',
            name='selected_city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='distance_to_center_km',
        ),
        migrations.RemoveField(
            model_name='hotelreservation',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='tourreservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tourreservation',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourreservation',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('partner', 'Tour Partner'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('payment_succeeded', 'Payment succeeded'), ('booking_confirmed', 'Booking confirmed'), ('booking_cancelled', 'Booking cancelled')], default='pending_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='tour',
            name='categories',
            field=models.ManyToManyField(related_name='tours', to='api.activitycategory'),
        ),
        migrations.AlterField(
            model_name='tourreservation',
            name='hotel_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hotelreservation'),
        ),
        migrations.AlterField(
            model_name='tourreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='TourSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.tour')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('tax_number', models.CharField(max_length=50)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='funneldraft',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.destination'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='api.destination'),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='api.destination'),
        ),
        migrations.AddField(
            model_name='tour',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='api.partnercompany'),
        ),
        migrations.AddField(
            model_name='tourreservation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='api.toursession'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.destination'),
        ),
    ]
