# Generated by Django 4.2.29 on 2026-04-06 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_destination_remove_funneldraft_selected_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.hotelreservation')),
                ('tour_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.tourreservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='reservationreview',
            constraint=models.UniqueConstraint(condition=models.Q(('hotel_reservation__isnull', False)), fields=('user', 'hotel_reservation'), name='unique_user_hotel_review'),
        ),
        migrations.AddConstraint(
            model_name='reservationreview',
            constraint=models.UniqueConstraint(condition=models.Q(('tour_reservation__isnull', False)), fields=('user', 'tour_reservation'), name='unique_user_tour_review'),
        ),
    ]
