# Generated by Django 4.2.29 on 2026-04-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservationreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='includes_free_food_drinks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes_hotel_pickup_dropoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='location_link',
            field=models.URLField(blank=True),
        ),
    ]
