# Generated by Django 4.2.30 on 2026-09-28 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_normalize_activity_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='generation_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
