from django.urls import path
from api.views import (
    ActivityListView,
    FunnelDraftView,
    HotelReservationCreateView,
    HotelReservationWebhookView,
    HotelSearchView,
    LoginView,
    LogoutView,
    MeEligibleReviewReservationsView,
    MeLanguageView,
    MePasswordView,
    MeReservationsView,
    MeReservationVoucherView,
    MeReviewsView,
    MeView,
    PlanConfirmView,
    PlanCurrentView,
    PlanGenerateOptionsView,
    PlanListView,
    PlanRestartView,
    RefreshTokenView,
    RegisterView,
    SuggestCitiesView,
    TourReservationCreateView,
    TourSearchView,
)


urlpatterns = [
    path('auth/register/', RegisterView.as_view(), name='auth-register'),
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/token/refresh/', RefreshTokenView.as_view(), name='auth-token-refresh'),
    path('auth/logout/', LogoutView.as_view(), name='auth-logout'),
    path('me/', MeView.as_view(), name='me'),
    path('me/password/', MePasswordView.as_view(), name='me-password'),
    path('me/language/', MeLanguageView.as_view(), name='me-language'),
    path('me/reservations/', MeReservationsView.as_view(), name='me-reservations'),
    path('me/reservations/<str:reservation_id>/voucher/', MeReservationVoucherView.as_view(), name='me-reservation-voucher'),
    path('me/reviews/eligible-reservations/', MeEligibleReviewReservationsView.as_view(), name='me-eligible-reviews'),
    path('me/reviews/', MeReviewsView.as_view(), name='me-reviews'),
    path('funnel/draft/', FunnelDraftView.as_view(), name='funnel-draft'),
    path('activities/', ActivityListView.as_view(), name='activities'),
    path('ai/suggest-cities/', SuggestCitiesView.as_view(), name='suggest-cities'),
    path('hotels/search/', HotelSearchView.as_view(), name='hotels-search'),
    path('hotel-reservations/', HotelReservationCreateView.as_view(), name='hotel-reservation-create'),
    path('webhooks/hotel-reservations/', HotelReservationWebhookView.as_view(), name='hotel-reservation-webhook'),
    path('tours/search/', TourSearchView.as_view(), name='tours-search'),
    path('tour-reservations/', TourReservationCreateView.as_view(), name='tour-reservation-create'),
    path('plans/', PlanListView.as_view(), name='plans-list'),
    path('plans/generate-options/', PlanGenerateOptionsView.as_view(), name='plans-generate-options'),
    path('ai/plans/generate/', PlanGenerateOptionsView.as_view(), name='plans-generate-legacy'),
    path('plans/confirm/', PlanConfirmView.as_view(), name='plans-confirm'),
    path('plans/current/', PlanCurrentView.as_view(), name='plans-current'),
    path('plans/restart/', PlanRestartView.as_view(), name='plans-restart'),
]